### PR TITLE
Cleaned syntax, normalized code to ES6, and more

### PR DESCRIPTION
**Pull request by qexat**
# Pull Request

## Description

- Cleaned the syntax
- Normalized the code to ES6
- Enhanced some code practices
- Fixed some typos
- Added `help` npm script (`npm run help` is the same as `node index.js --help`)

No issue fixed

### Type of change

- [x] New unbreaking feature (npm script)
- [x] Code cleaning, essentially

## How Has This Been Tested?

- `npm run help`
- `node index.js`
- `node index.js --help`
- `node index.js {path_to_repository}/tests/domains.txt 200 string`

> Note: `path_to_repository` looks like `/home/{user}/.../`

**Test Configuration**:
* OS: Endeavour 5.15.12-arch1-1 (64-bit)
* Node: 16.6.1 (npm 7.20.3)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] ~~I have added tests that prove my fix is effective or that my feature works~~ (not applicable)
- [ ] ~~New and existing unit tests pass locally with my changes~~ (not applicable)

### CODE REVIEW

**Comment by qexat** [comment]
The way how callback functions work on requests make difficult writing tests. I first tried then abandoned, but it should be implemented with a workaround and ran for every commit/PR with a workflow.

**Comment by umair9747** [comment]
Heya Clarisse!
First of all thank you so much for your PR, glad to see someone taking an interest in enhancing this tool!
I will be going through all the code changes as well as the tool's execution just to make sure there's no bug that could potentially affect it during runtime. If everything goes right, I will be accepting this asap.

Cheers,
Umair

**Comment by umair9747** [comment]
Heya Clarisse!

I went through the code and I must say it has been really well written and documented and hence I am accepting this Pull Request. Thank you so much for your contribution and I look forward to seeing more contributions in future! :)

Cheers,
Umair

**Comment by qexat** [comment]
You're welcome!

**Pull request merged**
